### ISSUE TITLE
Action simplification

### ISSUE THREAD

**Issue by AlexAegis** [puku0x/ngrx-todo#1]
Hi! Nice repo! it's really helping me on my thesis project.

I have a comment about your `todo.actions.ts` file.

I've found it a hassle to not just create the action, but also include it in the `union` function.

So I moved this logic out, to the `index.ts`, like this:

```typescript
import * as actions from './foo.actions';

import { union } from '@ngrx/store';

const all = union(actions);

export type FooActions = typeof all;

export * from './foo.actions';
```

And then the only things left in the `foo.actions.ts` file is the actual actions and I only have to define them there.

What do you think?

**Comment by puku0x** [comment]
@AlexAegis Thank you for your feedback.

It looks nicer than the current code. However, NgRx v8 provided `createAction` and it made action simpler to write. So I'm trying to migrate from v7 to v8 now. I appreciate your patience as it might take some time!

**Comment by puku0x** [comment]
Now all actions are created by `createAction` and they look much simpler than before. I will close this issue.
